# Generated by Django 4.1.1 on 2022-10-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_remove_index_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_user',
            name='gsm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index_user',
            name='prefix_gsm',
            field=models.IntegerField(),
        ),
    ]
