# Generated by Django 4.1.1 on 2022-09-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator_account', '0003_remove_index_collaborator_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join_table',
            name='id_collaborator',
        ),
        migrations.DeleteModel(
            name='Index_collaborator',
        ),
        migrations.DeleteModel(
            name='Join_table',
        ),
    ]
