# Generated by Django 4.1.1 on 2022-09-28 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_collaborator', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('birthday', models.DateField()),
                ('street', models.CharField(max_length=100)),
                ('number_street', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('town', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('prefix_gsm', models.PositiveIntegerField()),
                ('gsm', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
